# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.cache/wt [current_project]
set_property parent.project_path C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/new/accelerator_utils.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/csa_utils.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/CSA.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/final/MAC_8bits/MAC_8bits.srcs/sources_1/new/csa_acc_utils.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/final/MAC_8bits/MAC_8bits.srcs/sources_1/new/CSA_ACC.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/FA.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/LUT.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/rca_utils.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/RCA_4b.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Twos_complement_input.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/Twos_complement_output.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/dadda_utils.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/dadda_multi.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/imports/Codigo/ArtificialNeuron/ArtificialNeuron.srcs/sources_1/new/mux_2to1.vhd
  C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/sources_1/new/Accelerator.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/constrs_1/imports/Codigo_final/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Carmen/Desktop/Memoria/Codigo_VHDL/Accelerator/Accelerator.srcs/constrs_1/imports/Codigo_final/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Accelerator -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Accelerator.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Accelerator_utilization_synth.rpt -pb Accelerator_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
