# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Codigo_final/Nexys4DDR_Master.xdc

# IP: ip/clk_aux/clk_aux.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_aux || ORIG_REF_NAME==clk_aux} -quiet] -quiet
