webtalk_init -webtalk_dir C:/Users/Carmen/Desktop/TFG/Codigo_final/Accelerator_LG/Accelerator_LG.sim/sim_1/behav/xsim/xsim.dir/and8_lg_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun  9 19:19:11 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ac82c785-a679-4869-85c7-4aa0f00c5e37" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "150a9f3c3ea04019a798dc01e9f3b829" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 402340187 -regid "" -xml C:/Users/Carmen/Desktop/TFG/Codigo_final/Accelerator_LG/Accelerator_LG.sim/sim_1/behav/xsim/xsim.dir/and8_lg_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Carmen/Desktop/TFG/Codigo_final/Accelerator_LG/Accelerator_LG.sim/sim_1/behav/xsim/xsim.dir/and8_lg_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Carmen/Desktop/TFG/Codigo_final/Accelerator_LG/Accelerator_LG.sim/sim_1/behav/xsim/xsim.dir/and8_lg_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
